# Generated by Django 5.0.7 on 2024-09-01 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('producto_comprado', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Debito'), ('Tarjeta_de_Credito', 'Tarjeta de Credito')], default='', max_length=25)),
            ],
        ),
    ]
