# Generated by Django 5.0.7 on 2024-09-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Debito')], default='', max_length=25),
        ),
    ]
