# Generated by Django 4.2.13 on 2024-09-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_gasto_metodo_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
