# Generated by Django 3.2.25 on 2024-10-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_dinero_caja'),
        ('Ventas', '0005_venta_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='Caja.caja'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Débito'), ('Tarjeta_de_Credito', 'Tarjeta de Crédito')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
