# Generated by Django 5.1.1 on 2024-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_auto_20241001_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Débito'), ('Tarjeta_de_Credito', 'Tarjeta de Crédito')], default='', max_length=50),
        ),
    ]
