# Generated by Django 3.2.25 on 2024-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='caja',
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Debito'), ('Tarjeta_de_Credito', 'Tarjeta de Credito')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(default=0),
        ),
    ]
