# Generated by Django 3.2.25 on 2024-11-12 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0009_alter_productos_vendidos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_vendidos',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productos_vendidos',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
