# Generated by Django 4.2.13 on 2024-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
        ('Productos', '0020_alter_producto_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, null=True, through='Productos.Producto_Intermedia', to='Proveedores.proveedor'),
        ),
    ]
