# Generated by Django 3.2.25 on 2024-09-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
        ('Productos', '0028_alter_producto_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='punto_reposicion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, null=True, through='Productos.Producto_Intermedia', to='Proveedores.Proveedor'),
        ),
    ]
