# Generated by Django 4.2.13 on 2024-10-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0066_alter_producto_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo',
        ),
    ]
