# Generated by Django 3.2.25 on 2024-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0003_alter_proveedor_telefono'),
        ('Productos', '0079_alter_producto_precio_alter_producto_stock_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(through='Productos.Producto_Intermedia', to='Proveedores.Proveedor'),
        ),
    ]
