# Generated by Django 3.2.25 on 2024-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_alter_proveedor_email'),
        ('Productos', '0085_auto_20241113_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(through='Productos.Producto_Intermedia', to='Proveedores.Proveedor'),
        ),
    ]
