# Generated by Django 5.0.7 on 2024-08-25 16:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('saldo_inicial', models.IntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('saldo_final', models.IntegerField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
