# Generated by Django 3.2.25 on 2024-09-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_auto_20240910_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='saldo_negativo',
        ),
    ]
