# Generated by Django 3.2.25 on 2024-09-19 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Caja', '0003_remove_caja_saldo_negativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dinero', models.DateTimeField(default=datetime.datetime.now)),
                ('ing_egre', models.IntegerField(verbose_name='Ingreso/Egreso')),
                ('tipo_dinero', models.CharField(choices=[('', ''), ('Ingreso', 'Ingresar'), ('Egreso', 'Retirar')], default='', max_length=25)),
                ('id_sesion', models.CharField(default='', max_length=50)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
