# Generated by Django 3.2.25 on 2024-09-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0004_dinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinero',
            name='ing_egre',
            field=models.IntegerField(max_length=30, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='dinero',
            name='tipo_dinero',
            field=models.CharField(choices=[('', ''), ('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='', max_length=25, verbose_name='Tipo de movimiento'),
        ),
    ]
