# Generated by Django 3.2.25 on 2024-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0005_auto_20240925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinero',
            name='ing_egre',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
