# Generated by Django 3.2.25 on 2024-10-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0006_alter_dinero_ing_egre'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinero',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinero', to='Caja.caja'),
        ),
    ]
