# Generated by Django 3.2.25 on 2024-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_dinero_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='cerrada', max_length=10),
        ),
    ]
