# Generated by Django 3.2.25 on 2024-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0009_auto_20241001_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='dinero',
            name='caja',
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinero',
            name='ing_egre',
            field=models.IntegerField(verbose_name='Ingreso/Egreso'),
        ),
        migrations.AlterField(
            model_name='dinero',
            name='tipo_dinero',
            field=models.CharField(choices=[('', ''), ('Ingreso', 'Ingresar'), ('Egreso', 'Retirar')], default='', max_length=25),
        ),
    ]
