# Generated by Django 3.2.25 on 2024-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0010_auto_20241002_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10),
        ),
    ]
