# Generated by Django 3.2.25 on 2024-10-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0013_remove_dinero_fecha_dinero'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dinero',
            name='fecha_dinero',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
