# Generated by Django 3.2.25 on 2024-10-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0016_alter_caja_fecha_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 13, 16, 33, 399222)),
        ),
    ]
