# Generated by Django 4.2.13 on 2024-10-24 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0018_alter_caja_fecha_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
