# Generated by Django 4.2.13 on 2024-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0019_alter_caja_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
