# Generated by Django 3.2.25 on 2024-10-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_dinero_caja'),
        ('Compras', '0006_compra_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Caja.caja'),
        ),
    ]
