# Generated by Django 5.0.7 on 2024-10-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_compra_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_intermedio',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
