# Generated by Django 5.1.1 on 2024-10-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_compra_caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='empleado',
            new_name='usuario',
        ),
    ]
