# Generated by Django 5.1.1 on 2024-10-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_alter_compra_intermedio_cantidad'),
        ('Compras', '0008_rename_empleado_compra_usuario'),
    ]

    operations = [
    ]
