# Generated by Django 5.1.1 on 2024-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_merge_20241023_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='usuario',
            new_name='empleado',
        ),
        migrations.AlterField(
            model_name='compra_intermedio',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
