# Generated by Django 4.2.13 on 2024-10-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0010_rename_usuario_compra_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Debito')], default='', max_length=25),
        ),
    ]
