# Generated by Django 4.2.13 on 2024-10-28 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0011_alter_compra_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta_de_Debito', 'Tarjeta de Debito')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='compra_intermedio',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compra_intermedio',
            name='precio_de_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
