# Generated by Django 5.1.1 on 2024-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_alter_proveedor_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
