# Generated by Django 3.2.25 on 2024-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField()),
                ('razon_gasto', models.CharField(max_length=50)),
                ('desc_gasto', models.CharField(max_length=100)),
                ('monto_gasto', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
