# Generated by Django 3.2.25 on 2024-09-09 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion_gasto', models.CharField(max_length=100)),
                ('costo_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_gasto', models.CharField(choices=[('', ''), ('extraccion', 'EXTRACCION'), ('compra', 'COMPRA')], default='', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
    ]
