# Generated by Django 3.2.25 on 2024-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0002_auto_20240909_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='id_sesion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
