# Generated by Django 3.2.25 on 2024-09-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gastos', '0003_gasto_id_sesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='costo_cantidad',
            new_name='costo',
        ),
        migrations.AddField(
            model_name='gasto',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('', ''), ('INSUMOS', 'Insumos')], default='', max_length=25),
        ),
    ]
