# Generated by Django 3.2.25 on 2024-09-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0004_auto_20240918_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('', ''), ('insumos', 'INSUMOS')], default='', max_length=25),
        ),
    ]
