# Generated by Django 4.2.13 on 2024-09-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0005_alter_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tipo_gasto',
        ),
    ]
