# Generated by Django 3.2.25 on 2024-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0007_gasto_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='caja',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion_gasto',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
